name: doc_pat_track
description: "Application for adding, updating and retreiving patients of doctor"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Localizations
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  turkmen_localization_support: ^0.0.7

  # Navigation
  auto_route: ^7.8.4

  # Svg
  flutter_svg: ^2.0.2

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # DI
  get_it: ^7.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

   # DB
  hive_generator: ^2.0.0

  # Generator
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.2
  build_verify: ^3.1.0

  # Router
  auto_route_generator: ^7.3.2

  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/generated
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy_medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy_regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy_light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/shared/localizations
